export enum State {
  GAME_STARTED = 'GAME_STARTED',
  TAKING_BETS = 'TAKING_BETS',
  ROUND_IN_PROGRESS = 'ROUND_IN_PROGRESS',
  CRASHED = 'GAME_CRASHED',
  OFF = 'OFF',
}

export enum EventType {
  CHANGE_STATE = 'CHANGE_STATE',
}
